### ISSUE TITLE
I like this. But I have a question.

### ISSUE THREAD

**Issue by YoungsoonLee** [marklagendijk/node-pm2-windows-startup#1]
I like this. Thank you. But I have a question.

When I did pm2 save and windows server restarted , pm2 not started before login.
How can i solve this problem?

I added this(wscript.exe "C:\Users\youngsoonl\AppData\Roaming\npm\node_modules\pm2-windows-startup\invisible.vbs" "C:\Users\youngsoonl\AppData\Roaming\npm\node_modules\pm2-windows-startup\pm2_resurrect.cmd") to registry into LOCAL_MACHINE , But It was not working when server restart automatically before login.

**Comment by dlbrown06** [comment]
+1

I got so excited when I first found this module - only shortly to be let down finding out that in order for it to work the user had to login. Big let down. This could be a huge module for users forced to deploy node on windows too!

**Comment by jancervinka** [comment]
+1

Did anyone solve this?

**Comment by dlbrown06** [comment]
Nope - Forever is working for me in production. If the PM2 folks ever get around to fixing this, I may switch back, the forever solution is working for me with no headaches or work arounds

**Comment by marklagendijk** [comment]
This is indeed an issue. I opened #2 to solve this.

**Comment by jancervinka** [comment]
Just FYI, for now I solved it using Autologon https://technet.microsoft.com/en-us/sysinternals/bb963905

**Comment by Ampakinetic** [comment]
I've just created a windows service runner for PM2 if anyone is interested, I needed it for a project I'm working and have used os-service for other things and found it's very solid. 

https://github.com/Ampakinetic/pm2-windows-service
