### ISSUE TITLE
Office Scan detects malware in the package

### ISSUE THREAD

**Issue by gsokhran** [marklagendijk/node-pm2-windows-startup#14]
Hello,

When I am trying to download this package my office scan antivirus detects (see snapshot) and deletes the following malware - HackTool.VBS.InviBat.A [(more info)](https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/HackTool.VBS.InviBat.A).
The virus is found in the file - invisible.vbs .
![scan_snapshot](https://user-images.githubusercontent.com/43243755/62833013-14859500-bc38-11e9-8682-6364fe841372.png)

**Comment by catchnthrow** [comment]
Same thing for me as well.

**Comment by marklagendijk** [comment]
You can check the contents of `invisible.vbs` yourself. It will be the same as the one in this repo, and is very simple to understand.
